web:
  image: lwieske/java-8
  volumes:
   - .:/app
  ports:
   - 8888:8080
  links:
   - db
  entrypoint: /app/start.sh
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: Passw0rd
    POSTGRES_DB: conflab-test