web:
  build: .
  volumes:
   - .:/app
  ports:
   - 8080:8080
  links:
   - db
  environment:
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
db:
  image: postgres
  volumes:
   - ./db_data:/var/lib/postgresql/data
  ports:
   - 5433:5432
  environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: conflab